packaging_format = 2

id = "blogotext"
name = "BlogoText"
description.en = "Lightweight Blog-Engine"
description.fr = "Moteur de blog léger"

version = "3.7.6~ynh6"

maintainers = ["Antoine"]

[upstream]
license = "MIT"
website = "https://blogotext.org/"
demo = "https://blogotext.org/blog/"
admindoc = "https://github.com/BlogoText/blogotext/wiki"
code = "https://github.com/BlogoText/blogotext"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/blogotext"

    [install.admin]
    type = "user"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.language]
    ask.en = "Choose the application language"
    ask.fr = "Choisissez la langue de l'application"
    type = "select"
    choices = ["fr", "en"]
    default = "fr"

    [install.password]
    type = "password"

[resources]
        [resources.sources.main]
        url = "https://github.com/BlogoText/blogotext/archive/fa2a4497e76aeb295db1a9d1aa8b7594c7484365.tar.gz"
        sha256 = "14098f6a1d1f1ef9569ddaf79bb2e29fe88b810d6831eb3de620297dea4ee4c2"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "mariadb-server, php8.2-mysql, php8.2-xml, php8.2-intl, php8.2-mbstring, php8.2-gd, php8.2-curl"

    [resources.database]
    type = "mysql"
